#!/usr/bin/env python
#
#
import sys,os,thread,threading
from subprocess import call

def getDatetime():
	return (os.popen("date +\"%Y%m%d:%H%M%S\"").readline().replace("\n","").strip())

_CurDatetime = getDatetime()
_CurMinute=int(_CurDatetime [11:13])

update_rpi_sensor=0
update_twitter=0
update_xively=0

#print (_CurDatetime ,_CurMinute, _CurMinute % 5)	

if ((_CurMinute % 2)==0):	# on every 2Minutes
	print ("2 minutes trigger")
	update_rpi_sensor=1

if ((_CurMinute % 5)==0):	# on every 5Minutes
	print ("5 minutes trigger")
	update_twitter=1
	update_xively=1

if ((_CurMinute % 15)==0):	# on every 15Minutes
	print ("15 minutes trigger")
	update_rpi_sensor=1
	
if ((_CurMinute % 30)==0):	# on every 30Minutes
	print ("30 minutes trigger")
	update_rpi_sensor=1

if (_CurMinute ==0):	# on every 60Minutes
	print ("60 minutes trigger")
	update_rpi_sensor=1


# Add event into rpi_log record

if (update_rpi_sensor==1):
    call(['rpi-sensor.py'])

if (update_twitter==1):
    call(['rpi-log.py', "update_twitter", "cron.rpi"])

if (update_xively==1):
    call(['rpi-log.py', "update_xively", "cron.rpi"])

